[package]
name = "sha256-wrapper"
version = "0.1.0"
edition = "2021"
#links = ["openssl", "crypto"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
hex = "0.4"

[build-dependencies]
bindgen = "0.59.2"
